name: Update
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}
        persist-credentials: true
    - run: echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Test</title></head><body><h1>UPDATED</h1></body></html>' > index.html
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add index.html
        git commit -m "auto update"
        git push origin ${{ github.ref_name }}
