name: AutoUpdate
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "<h1>TEST $(date +%s)</h1>" > index.html
      - run: cat index.html
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add -f index.html
      - run: git commit -m "update $(date +%s)"
      - run: git push origin main --force
