name: UpdateSite
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo "<h1>Site Updated</h1>" > index.html
    - run: git config user.name github-actions
    - run: git config user.email github-actions@github.com
    - run: git add index.html
    - run: git commit -m "Auto update"
    - run: git push origin main
